name: math168
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - networkx
  - jupyter
  - jupyterlab
  - ipykernel
  - scikit-learn
  - python-louvain
  - pip
  - pip:
    - group-lasso
